use_frameworks!

platform :ios, '8.0'

target 'SSVerifyCodeView_Example' do
  pod 'SSVerifyCodeView', :path => '../'
  pod 'Masonry'
  
  target 'SSVerifyCodeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
